### ISSUE TITLE
Extension error on lines 418 finding msizap

### ISSUE THREAD

**Issue by Lintnotes** [LFM8787/PSADT.MSIZap#1]
Hi Great tool and works awesome love the extension just to note i had to copy the PSADT.MSIZap folder to both the Toolkit directory and the supportfiles directory for it to fully function just wanted to bring that up. 

Thanks,
Brandon

**Comment by LFM8787** [comment]
Hi there, it is not an issue, check the line 419:

"Unable to locate msizap.exe application, the required file must be located under [..\SupportFiles\PSADT.MSIZap\] directory."

Ensure you are extracting the zip file content inside Toolkit folder.

The requiree files and relative paths are in the zip file :)
